export { Home } from './Home'
export { About } from './About'
export { Learning } from './Learning'
export { Profile } from './Profile'
export { X9 as Login } from './🔐'
export { Diagnostico } from './Diagnostico'
export { ExpertAnnotations } from './ExpertAnnotations'
